### ISSUE TITLE
Need clarification on t13-expected.xml for snapshot generation tests

### ISSUE THREAD

**Issue by riolex** [FHIR/fhir-test-cases#95]
There are couple of things in test case t13 ([t13-expected.xml](https://github.com/FHIR/fhir-test-cases/blob/700002791723215baf61913810bedef3e620988f/r5/snapshot-generation/t13-expected.xml)) which I find suspicious. They seem wrong to me, but I could be mistaken.

It looks like slices for `code` and `period` (which come from http://hl7.org/fhir/extension-patient-nationality.json.html profile) are not merged correctly into `"Patient.extension:complex`.

Here is the list of things which I think are not correct for [`code`](https://github.com/FHIR/fhir-test-cases/blob/700002791723215baf61913810bedef3e620988f/r5/snapshot-generation/t13-expected.xml#L647) slice:

1. [Short and definition](https://github.com/FHIR/fhir-test-cases/blob/700002791723215baf61913810bedef3e620988f/r5/snapshot-generation/t13-expected.xml#L650-L651) read "Nationality" and "The nationality of the patient." instead of "Nationality Code" and "Code representing nationality of patient." (as per profile).
2. [max](https://github.com/FHIR/fhir-test-cases/blob/700002791723215baf61913810bedef3e620988f/r5/snapshot-generation/t13-expected.xml#L653) reads "*" whereas in nationality profile it reads "1".
3. Few other minor things (like presence of "condition" which shouldn't be there, "isSummary" is not present but should be `false`.

Same thing for `period`.

It looks like these slices (which are slices on `Extension.extension` coming from http://hl7.org/fhir/StructureDefinition/patient-nationality) get merged from Extension root.

Am I missing something?

**Comment by riolex** [comment]
Oh, and another thing is that [t13-input.xml](https://github.com/FHIR/fhir-test-cases/blob/700002791723215baf61913810bedef3e620988f/r5/snapshot-generation/t13-input.xml) uses `<profile value="http://hl7.org/fhir/StructureDefinition/patient-nationality#code"/>` reference. Should it be `<profile value="http://hl7.org/fhir/StructureDefinition/patient-nationality#Extension.extension:code"/>` instead (id of the element is `Extension.extension:code` rather than just `code`?

**Comment by grahamegrieve** [comment]
are these things still a problem (and sorry I missed this for so long)
